### ISSUE TITLE
Adding CoC to the repo and a link in the page footer

### ISSUE THREAD

**Issue by heliocola** [rubytogether/rubytogether.org#16]
Hi there,
I started working on adding a Contributor Convenant CoC to the RubyTogether repo.
You can check it here: https://github.com/heliocola/rubytogether.org/commit/9103be989f90c0814b529db781a44df014a24952

But I also think it deserves a link in the footer perhaps between STORE and FAQ.
If you guys agree with that I can make the changes and send the PR.

Thanks,
Helio

**Comment by indirect** [comment]
This looks great! To add a CoC to Ruby Together itself, we'll need different language (since members are not exactly contributors). I think the Bundler CoC is probably a good community CoC to start from. Go ahead and send this as a PR for the website repo, and we can work on the RT community CoC separately.

**Comment by heliocola** [comment]
Ok. It is on its way to you.

**Comment by indirect** [comment]
Cherry-picked in cabe187454156ffc27a02f5ba5975fddb6c3ce79.
